- name: サーバ再起動
  hosts: web db
  gather_facts: false

  tasks:
    - name: connect check
      ping:

    - name: restart server
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      become: true
      ignore_errors: true

    - name: wait for reboot
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: connect check
      ping:

    - name: check uptime
      shell: uptime
      register: result
    - name: show previous shell stdout
      debug:
        msg: "{{ result.stdout }}"
